// <auto-generated />
using System;
using EatDomicile.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatDomicile.Core.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250903134743_Orders_Drink")]
    partial class Orders_Drink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatDomicile.Core.Models.Dough", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Doughs");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Drink", b =>
                {
                    b.HasBaseType("EatDomicile.Core.Models.Product");

                    b.Property<bool>("Fizzy")
                        .HasColumnType("bit");

                    b.Property<int>("KCal")
                        .HasColumnType("int");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Food", b =>
                {
                    b.HasBaseType("EatDomicile.Core.Models.Product");

                    b.Property<bool>("Vegetarien")
                        .HasColumnType("bit");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Burger", b =>
                {
                    b.HasBaseType("EatDomicile.Core.Models.Food");

                    b.ToTable("Burgers");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Pasta", b =>
                {
                    b.HasBaseType("EatDomicile.Core.Models.Food");

                    b.Property<int>("KCal")
                        .HasColumnType("int")
                        .HasColumnName("Kcal");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.ToTable("Pastas");
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Pizza", b =>
                {
                    b.HasBaseType("EatDomicile.Core.Models.Food");

                    b.Property<int>("DoughId")
                        .HasColumnType("int");

                    b.HasIndex("DoughId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatDomicile.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Drink", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("EatDomicile.Core.Models.Drink", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Food", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("EatDomicile.Core.Models.Food", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Burger", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Food", null)
                        .WithOne()
                        .HasForeignKey("EatDomicile.Core.Models.Burger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Pasta", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Food", null)
                        .WithOne()
                        .HasForeignKey("EatDomicile.Core.Models.Pasta", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatDomicile.Core.Models.Pizza", b =>
                {
                    b.HasOne("EatDomicile.Core.Models.Dough", "Dough")
                        .WithMany()
                        .HasForeignKey("DoughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatDomicile.Core.Models.Food", null)
                        .WithOne()
                        .HasForeignKey("EatDomicile.Core.Models.Pizza", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dough");
                });
#pragma warning restore 612, 618
        }
    }
}
